### ISSUE TITLE
Commit pre-commit script adds extraneous newline.

### ISSUE THREAD

**Issue by halfnibble** [skovy/typed-scss-modules#65] opened 2020-04-08 00:01 UTC
When running prettier or git commit (which must be running prettier?) an extraneous newline is added to the README.md file here:
https://github.com/skovy/typed-scss-modules/blame/0a92eee7545cfedadd8265c82faff4fcd413f059/README.md#L231

## Expected Behavior

I expect it not to add an extraneous newline.

## Current Behavior

A newline is added, which caused a somewhat confusing merge conflict. 

## Possible Solution

Either figure out how master got to a state where the newline is missing, or add some rule to a prettier config to not auto-add a newline there?

## Steps to Reproduce (for bugs)

1. Checkout current master (0a92eee7545cfedadd8265c82faff4fcd413f059)
2. Run `yarn check-formatting` and see the error. 
3. Make any change and run git commit. Notice the extra newline in the README.md file.

## Context

Trying to contribute a PR. 

## Your Environment

- MacOS 10.15.4
- node v10.16.3

**Comment by skovy** [comment] 2020-04-08 00:25
ah crap, sorry about that @halfnibble. 

The problem is the all contributors PRs I merged earlier today. I didn't look at the build closely since it's only changes to the README but something isn't adhering to Prettier. (might need to update Prettier).

This should be fixed now with https://github.com/skovy/typed-scss-modules/commit/c14c83fbd10b01e77250f42d0a4dee9303c7d34c

I'll handle merging your PR.

**Closed by skovy** 2020-04-08 00:25 UTC

**Comment by halfnibble** [comment] 2020-04-08 00:31
No problem. :)
