### ISSUE TITLE
Watch option says "File not found or unreadable" on Windows

### ISSUE THREAD

**Issue by RobbieGM** [skovy/typed-scss-modules#38] opened 2019-09-01 14:54 UTC
Hi,
I realize you just released a version (0.0.12) that is supposed to fix this, but for me, when using the watch option, I still get an error saying "File not found or unreadable" on Windows. However, it generates the types correctly the first time I run the command. I am using version 0.0.12 on Windows with Git Bash as my terminal in VS Code.
![image](https://user-images.githubusercontent.com/15571556/64078283-9badb200-cca6-11e9-9858-1a80b740b5c6.png)
Thank you for your time!

**Comment by skovy** [comment] 2019-09-03 02:33
@RobbieGM did `0.0.11` work for you?

@lkarmelo any ideas what might be causing this issue? (asking you because of https://github.com/skovy/typed-scss-modules/pull/34)

**Comment by RobbieGM** [comment] 2019-09-03 11:24
I tried 0.0.11 and it didn't do anything when the files changed. When the error shows, it uses forward slashes instead of Windows backslashes. Could that be it?

**Comment by lkarmelo** [comment] 2019-09-03 17:13
Forward slashes should work fine on windows.
Google search shows the issue occurs when the file node-sass tries to write is already being accessed by another process. It seems to happen with VS Code, i use webstorm and have never ran into this problem.
https://github.com/sass/node-sass/issues/2022
https://github.com/sass/node-sass/pull/2386
https://github.com/microsoft/vscode/issues/20491
This library doesn't use node-sass watcher, but i believe, the reason behind the issue is the same. Maybe advices in links above will help

**Comment by burtek** [comment] 2020-01-16 13:07
Any progress on this? This really makes the job harder
@skovy

**Comment by skovy** [comment] 2020-01-16 13:55
Have you tried themost recent version? Some of the dependencies have been upgraded that are responsible for the watch functionally.

I unfortunately don't have access to a windows machine so I would need help reproducing and debugging to find the root cause, fix, and validate.

**Comment by burtek** [comment] 2020-01-16 14:03
I'm using 1.0.1 all the time and I'm randomly getting two kinds of errors:

```
[CHANGED] src\styles\style.module.scss
File to read not found or unreadable: C:/Projects/ProjectA/src/styles/style.module.scss
```
or
```
[CHANGED] src\styles\style.module.scss
File to import not found or unreadable: ~dependency/path/file.scss (C:/Projects/ProjectA/src/styles/_imports.scss)
```

**Comment by burtek** [comment] 2020-01-20 13:14
I guess the problem is with using `~` as alias to `node_module/` in imports. I've found https://github.com/sass/node-sass/issues/2796

Might this be the case?

**Comment by evangelinepapanicola** [comment] 2020-08-04 12:07
Any updates on this? I'm having this issue and it's driving me crazy. None the local patches floating around work for me. I randomly seemed to fix the issue on a different device months ago by simply uninstalling VSCode, deleting all related files and reinstalling. I'm about to try that on this device too but I have little hope considering I only installed VSCode for the first time on this device very recently.

**Comment by skovy** [comment] 2023-08-04 20:26
No updates in 3 years, closing. Please re-open with a reproduction if this is continuing to occur.

**Closed by skovy** 2023-08-04 20:26 UTC
Labels: bug
