### ISSUE TITLE
Generated css class name not in camel case (but yes in d.ts)

### ISSUE THREAD

**Issue by MikelArnaiz** [skovy/typed-scss-modules#21] opened 2019-03-29 13:52 UTC
I'm using this module in a project bootstrapped with `create-react-app`.

I added a script to my `package.json`: `"generate-dts": "npx tsm src/**/*.module.scss --watch",`

In my `App.module.scss` I have: 

```css
.with-dashes {
  color: red;
}
```

Which produces a camel case (👌) class name in the `App.module.scss.d.ts`:

```ts
export const withDashes: string;
```

That allows me to import the class in my `App.tsx`

```tsx
export const App = () => <h1 className={styles.withDashes}>With dashes</h1>
```
However  I don't see the text in red, if I inspect the HTML element I see that it doesn't even have a class name:

```html
<h1>With dashes</h1>
```

Inspecting the `head` element I can see why, the generated css class name **has** a dash. Typescript compiler thinks the class name is `withDashes` but it is `with-dashes`.

```html
<style type="text/css">
  .App_with-dashes__2Edt5 {color: red; }
</style>
```

### How do you solve this issue?
Is this something that have to be solved with `node-sass`? Notice I don't want to eject my `create-react-app` project, I don't have access to its internal webpack configuration.

I could generate `d.ts` files with dashes (`npx tsm src/**/*.module.scss --watch --nameFormat none --exportType default`) but I don't want to have to change all my `.tsx` files

**Comment by skovy** [comment] 2019-03-29 17:35
Hey @MikelArnaiz, the [`nameFormat` option](https://github.com/skovy/typed-scss-modules#--nameformat--n) should be what you need here.

It looks like the `--nameFormat none --exportType default` options like you mentioned should do the trick? Does this not work as expected?

**Comment by MikelArnaiz** [comment] 2019-04-02 14:49
Hi @skovy

Using those options I get:

```
export interface Styles {
  'with-dashes': string;
}
```

But then I have to use dash notation in my `.tsx`; 
```
className={styles["with-dashes"]}
```

and I want to use camelcase; 
```
className={styles.withDashes}
```

You can test it yourself https://github.com/MikelArnaiz/typed-scss-modules-test

Then run `npm run dts` or `dts-with-dashes`

**Comment by skovy** [comment] 2019-04-03 02:44
@MikelArnaiz a PR was recently merged to handle type generation for create-react-app: https://github.com/skovy/typed-scss-modules/pull/17

It added [this note](https://github.com/skovy/typed-scss-modules#--nameformat--n) to the `README`:

> Note: If you are using create-react-app v2.x and have NOT ejected, --nameFormat none --exportType default matches the class names that are generated in CRA's webpack's config.

From what I understand, if you wanted to use camel case you would have to eject and adjust the CSS Module configuration. This package (`typed-scss-modules`) only generates types following the format provided via the options (`nameFormat`, etc) and it's expected that those options will match the configuration of the tooling used for CSS Modules. It will only affect the compile time type checking and will not affect anything at runtime like converting the classnames to camelcase.

cc @dawnmist not sure if you have any insights to add here since some of your recent changes were for adding better support for CRA?

**Comment by dawnmist** [comment] 2019-04-03 08:17
@MikelArnaiz The problem is that create-react-app does _not_ enable/use the css loader options that create class names as camel-case. This then means that when webpack produces the list of style names from the css/scss file, there are no camel-case versions of variables with the final class-names generated.

When webpack then tries to plug the css class names into the tsx component file, the variable name in camel-case is undefined (css-loader in webpack didn't create the camel-case string variable), resulting in your html not having any class defined.

As far as I know, the only way to make the css class name strings be available in camel-case format is to change the webpack settings buried inside create-react-app's react-scripts package.

The critical part is at https://github.com/facebook/create-react-app/blob/9514cb88ab92fec7f5df2914702ef23a62c0a249/packages/react-scripts/config/webpack.config.js#L482-495 - the options parameter given to `getStyleLoaders` needs to have the option `camelCase` set to either `true` (to change all classes into camel-case) or `dashes` (to change only classes containing dashes into camel-case). Overall there are 4 places you'd probably want to alter - I've highlighted the scss modules one, but you'd probably want to update all the calls to `getStyleLoaders`.

For adding this option, you have a few options:
* Eject, then add to your own webpack config that ejecting generates - but you won't get any upgrades from react-scripts in future.
* Fork react-scripts, make the change in your fork, and use your own fork of react-scripts instead of the main one. This is generally the method that create-react-app recommends for a small change like this. You'll need to keep pulling updates from react-scripts in order to get updates.
* Use an npm module called [patch-package](https://github.com/ds300/patch-package#readme) to create a small patch to react-scripts that gets reapplied every time the react-scripts package is reinstalled. This is the method I usually use for small tweaks similar to this one.

Alternatively, use camel-case class names in your scss (which was what I decided to do), so Webpack does not need to alter the variable name it uses for the class name string variables.

**Comment by dawnmist** [comment] 2019-04-03 08:24
Just to make it clear - changing the types generation to anything that doesn't match Webpack's class-name generation will result in undefined values when you try to use those altered types. There is nothing at all that `typed-scss-modules` (or any other types-only generation package) can do to fix that mismatch. If you want different variable names being generated, you _must_ make sure that Webpack's config file is set up correctly to get them being generated the way that you wanted them to be.

**Closed** 2019-04-20 16:53 UTC
