### ISSUE TITLE
Watch mode serves only 1 folder

### ISSUE THREAD

**Issue by askirmas** [skovy/typed-scss-modules#40] opened 2019-10-03 12:16 UTC
```$ tsm "{pages,layouts,components}/**/[^_]*\.{css,scss}"```
Found 13 files. Generating type defintions...
[GENERATED TYPES] layouts/main/clips.css.d.ts
[GENERATED TYPES] layouts/main/CenterFlex.css.d.ts
[GENERATED TYPES] layouts/main/button.css.d.ts
[GENERATED TYPES] layouts/main/InternalGrid.css.d.ts
[NO GENERATED TYPES] layouts/main/scrollbar.css
**[GENERATED TYPES] pages/body.css.d.ts**
[GENERATED TYPES] layouts/main/text.css.d.ts
**[GENERATED TYPES] pages/body-top.css.d.ts**
**[GENERATED TYPES] pages/footer.css.d.ts**
**[GENERATED TYPES] pages/item-new.css.d.ts**
**[GENERATED TYPES] pages/item.css.d.ts**
[GENERATED TYPES] layouts/main/index.scss.d.ts
**[GENERATED TYPES] pages/main.scss.d.ts**
```$ tsm "{pages,layouts,components}/**/[^_]*\.{css,scss}" --watch```
Watching files...
[ADDED] layouts/main/CenterFlex.css
[ADDED] layouts/main/InternalGrid.css
[ADDED] layouts/main/button.css
[ADDED] layouts/main/clips.css
[ADDED] layouts/main/index.scss
[ADDED] layouts/main/scrollbar.css
[ADDED] layouts/main/text.css
[GENERATED TYPES] layouts/main/CenterFlex.css.d.ts
[GENERATED TYPES] layouts/main/InternalGrid.css.d.ts
[GENERATED TYPES] layouts/main/button.css.d.ts
[GENERATED TYPES] layouts/main/clips.css.d.ts
[NO GENERATED TYPES] layouts/main/scrollbar.css
[GENERATED TYPES] layouts/main/text.css.d.ts
[GENERATED TYPES] layouts/main/index.scss.d.ts

**Comment by skovy** [comment] 2019-10-10 02:03
Without an example to reproduce, my initial thought is the difference between the two is that the first command (without watch) is using `glob` to find the files whereas the second example is using `chokidar`. 

There's nothing custom for resolving the glob patterns in this repo, so it's likely a limitation of the package `chokidar` depends.

However, I do agree it's confusing that the two commands produce different outputs. I think it would be reasonable to either use `chokadir` even not when watching (haven't investigated the feasibility of this) or minimally using the same package to resolve the glob patterns.

This wouldn't fix this issue, but it would be consistent.

**Comment by skovy** [comment] 2019-12-08 20:48
Thanks again for reporting @askirmas and I'm looking into this issue. There are actually a number of things going on / several issues that I think all boil down to two issues:

- Using both `glob` and `chokidar`. Since `chokidar` provides a superset of functionality (both matching files and then actually watching for changes) I believe it makes sense to remove `glob` and rely solely on `chokidar` using it's `close()` method.
- `chokidar` appears to have issues in the version used by this package. However, `chokidar` has released a new major version that now relies on `picomatch` (not sure what it was before).

I believe consolidating both the one-off and the watch command to use the same package should minimally product deterministic behavior. Additionally, any remaining bugs can hopefully be reproduced at the `picomatch` library level. This should free this package (`typed-scss-modules`) from creating any non-deterministic or buggy behavior.

**Comment by skovy** [comment] 2022-02-15 02:50
`chokidar` has been upgraded and has received many updates. I'm closing this issue without a reproducible example.

**Closed by skovy** 2022-02-15 02:50 UTC
Labels: bug
