### ISSUE TITLE
File watcher does not detect changes to imported Sass files

### ISSUE THREAD

**Issue by srmagura** [skovy/typed-scss-modules#170] opened 2022-09-07 15:52 UTC
## Expected Behavior

If `index.module.scss` contains

```scss
@import './colors';
```

Then `typed-scss-modules --watch` should regenerate `index.module.scss.d.ts` if `colors.scss` changes.

## Current Behavior

`typed-scss-modules --watch` does NOT regenerate `index.module.scss.d.ts` if `colors.scss` changes.

As a workaround, just make a trivial edit to `index.module.scss`.

## Possible Solution

Not sure how to fix this, but I am happy to attempt a PR if you are open to it. 😃

## Steps to Reproduce (for bugs)

Minimal repro with instructions: https://github.com/srmagura/typed-scss-modules-watch-repro

## Context

I have an `index.module.scss` that imports many other Sass files. I want `index.module.scss.d.ts` to be regenerated when any of those Sass files change, since this affects the TypeScript declarations that are produced.

## Your Environment

- Version used: 6.5.0
- Operating System and versions: macOS 12.5.1
- Link to your project: https://github.com/srmagura/typed-scss-modules-watch-repro

**Comment by skovy** [comment] 2022-09-07 22:52
Closing as a duplicate of https://github.com/skovy/typed-scss-modules/issues/46.

As discussed in that issue, there is no known trivial way to solve this efficiently (suggestions welcome!). However, a simple (but inefficient) solution would be to allow an option to rebuild everything which I think would be a reasonable contribution if it solves your problem (not sure if it will be fast enough in practice).

If you have any ideas, feedback, etc. comment on the linked issue and we can re-open it if needed.

**Closed by skovy** 2022-09-07 22:52 UTC
